name: CI
on:
  workflow_dispatch:

jobs:
  build:
    name: Update JSON
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}

      - name: Set Node.js 22.12.x
        uses: actions/setup-node@v3
        with:
          node-version: 22.12.x

      - name: Run install
        uses: borales/actions-yarn@v5
        with:
          cmd: install # will run `yarn install` command
      - name: Update JSON DB
        uses: borales/actions-yarn@v5
        env:
          VITE_DOWNLOAD_URL: ${{ secrets.VITE_DOWNLOAD_URL }}
        with:
          cmd: updateJsonDb # will run `yarn updateJsonDb` command
      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Update JSON
